### ISSUE TITLE
Current season schedule not export expected number of rows

### ISSUE THREAD

**Issue by tbrittain** [tbrittain/SMB3Explorer#165]
There are more rows than expected exported. I can run a 162 game 30 team season, and the total number of games should be 2430. Instead, the actual number is upwards of 2500. Some rows must be duplicated

**Comment by DantheChef** [comment]
Hi! There definitely are a bunch of duplicates, I couldn't really see any pattern besides the team but here's a bunch of them!

![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/3701a5c6-92ba-4429-8747-79862f6e0e71)
![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/2854bb45-0562-413c-b39e-0e6aafa495bf)

![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/ab05ebc5-79a3-4e8c-ab46-54589ab506d1)
![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/4c5fc9b6-4615-4d47-acfb-c79d3305f5b0)

![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/9c90ce4a-28e2-4a00-ac38-b5aab5565926)
![image](https://github.com/tbrittain/SMB3Explorer/assets/26890375/5db3ff95-e783-4ce7-9ae9-b1ac5c256a0a)

[SMB3Explorer.csv](https://github.com/tbrittain/SMB3Explorer/files/12544010/SMB3Explorer.csv)

**Comment by tbrittain** [comment]
Thanks for this, luckily I have been able to reproduce locally. Haven't been able to fix it just yet, but this is a high priority item, so hopefully within the next couple of days

**Comment by tbrittain** [comment]
@DantheChef I have fixed the issue. About to create a new release (1.6.2) with the fix. Be sure to download it when you see it live

**Comment by DantheChef** [comment]
Thanks, will do! I appreciate it!
